CREATE OR ALTER PROC CreateProductRewardTable
AS
BEGIN

	CREATE TABLE ProductRewards
	(
		Id UNIQUEIDENTIFIER PRIMARY KEY,
		DateId SMALLINT NOT NULL FOREIGN KEY REFERENCES Dates(Id),
		ProductId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Products(Id),
		Reward INT NOT NULL CHECK (Reward >=0),
		DeletedAt DATETIME2,
		ModifiedAt DATETIME2,
		CreatedAt DATETIME2 NOT NULL
	)

END
