CREATE OR ALTER PROC CreateProductsTable
AS
BEGIN
	CREATE TABLE Products
	(
		Id UNIQUEIDENTIFIER PRIMARY KEY,
		Name NVARCHAR(256) NOT NULL UNIQUE,
		DeletedAt DATETIME2,
		ModifiedAt DATETIME2,
		CreatedAt DATETIME2 NOT NULL
	)
END