CREATE OR ALTER PROC CreateUserRolesTabel
AS
BEGIN
	CREATE TABLE UserRoles
	(
		Id UNIQUEIDENTIFIER PRIMARY KEY,
		UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(Id),
		RoleId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Roles(Id)
	)

END
